name: flutter_onboard
description: A simple, elegant and easy to use onboard widget for both android and ios devices.
version: 0.1.0
homepage: https://github.com/mohanasundaramn/ms-flutter-packages
repository: https://github.com/mohanasundaramn/ms-flutter-packages/tree/master/flutter_onboard

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
